[#topics/graphs/custom-graphs]

## Creating Custom Graphs

To create a custom graph, derive from <<reference/instruction-graph.html,InstructionGraph>> and implement the abstract method `Run(InstructionStore variables)`. The following is an example of a graph that has three different entry points and runs them sequentially:

[source,cs]
----
	public class ScopedGraph : InstructionGraph
	{
		<1>
		public InstructionGraphNode Enter = null;
		public InstructionGraphNode Process = null;
		public InstructionGraphNode Exit = null;

		protected override IEnumerator Run(InstructionStore variables)
		{
			<2>
			yield return Run(variables, Enter, nameof(Enter));
			yield return Run(variables, Process, nameof(Process));
			yield return Run(variables, Exit, nameof(Exit));
		}
	}
----

<1> <<reference/intruction-graph-node.html,InstructionGraphNode>> fields on a graph will automatically be added as output options visually for a graph in the Instruction Graph Window.

<2> Internally, graphs operate as a https://docs.unity3d.com/ScriptReference/Coroutine.html[Coroutine^] which gives fine control of timing behaviour. Because of this, it is important to `yield` the execution of each entry node that this graph will run. The third parameter is simply a label used in debugging for tracking the flow of execution in the Instruction Graph Window.

Ultimately, graphs are just a https://docs.unity3d.com/ScriptReference/ScriptableObject.html[Asset^] so they can store data and implement any functionality desired. Execution will end when the `Run()` function finishes.
