[#topics/graphs/custom-nodes]

## Creating Custom Nodes

To create custom nodes, derive from <<reference/instruction-graph-node.html,InstructionGraphNode>> and implement the abstract method `Run(InstructionGraph graph, InstructionStore variables, int iteration)`. The following is an example of a custom node that instantiates a game object from a prefab and stores it in a <<reference/variable-reference,variable reference>>.

[source,cs]
----
	public class SpawnObjectNode : InstructionGraphNode
	{
		public InstructionGraphNode Next = null; <1>
		public GameObjectVariableSource Prefab = new GameObjectVariableSource();
		public VariableReference ObjectVariable = new VariableReference();
		
		public override IEnumerator Run(InstructionGraph graph, InstructionStore variables, int iteration) <2>
		{
			if (ResolveObject(variables, Prefab, out GameObject prefab)) <3>
			{
				var spawned = Instantiate(prefab);

				Assign(variables, ObjectVariable, VariableValue.Create(spawned)); <4>
			}

			graph.GoTo(Next, nameof(Next)); <5>

			yield break;
		}
	}
	
----

<1> <<reference/intruction-graph-node.html,InstructionGraphNode>> fields on a node will automatically be added as branch options for that node in Instruction Graph Window.
<2> The third parameter _iteration_ will increment if this node is an <<reference/i-sequence-node.html,ISequenceNode>> or an <<reference/i-loop-node.html,ILoopNode>> every time this node is run.
<3> Numerous `Resolve()` helper methods are provided on the base <<reference/instruction-graph-node.html,InstructionGraphNode>> class to simplify retrieving typed objects from <<reference/variable-reference.html,variable references>> and <<reference/variable-source,variable sources>>.
<4> The `Assign()` helper method is also provided for setting <<reference/variable-value,values>> to <<reference/variable-reference,references>>
<5> Call `graph.GoTo()` to tell the graph that this node has finished performing its actions. If the passed node is `null`, or if `graph.GoTo()` is not called before the run method finishes, then the graph will finish. The second parameter is simply a label used in debugging for tracking the flow execution in the Instruction Graph Window